name: 'Setup'
description: 'Setup node/pnpm version and install dependencies'


runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: "8.x"
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.tool-versions'
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
        registry-url: "https://registry.npmjs.org"
    - name: Install Google Fonts
      run: |
        wget -O Fira_Sans.zip https://fonts.google.com/download?family=Fira%20Sans
        unzip -d fira_sans/ Fira_Sans.zip
        mv fira_sans /usr/share/fonts/
        fc-cache -fv
      shell: bash
    - name: Install Hugo
      env:
        HUGO_VERSION: 0.117.0
      run: |
        HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        mkdir $HOME/bin
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
        tar xvzf ${HUGO_DOWNLOAD} hugo
        mv hugo $HOME/hugo
      shell: bash
