name: Setup
description: Setup node/pnpm version and install dependencies

inputs:
  hugo_version:
    description: 'AWS Access Key ID'
    required: true

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: "8.x"
    - uses: actions/setup-node@v3
      with:
        node-version-file: .tool-versions
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
        registry-url: "https://registry.npmjs.org"

    # Cache for Google Fonts
    - name: Cache Google Fonts
      id: cache-fonts
      uses: actions/cache@v3
      with:
        path: /usr/share/fonts
        key: google-fonts-${{ inputs.hugo_version }}
    - name: Install Google Fonts
      if: steps.cache-fonts.outputs.cache-hit != 'true'
      run: |
        wget -O Fira_Sans.zip https://fonts.google.com/download?family=Fira%20Sans
        unzip -d fira_sans/ Fira_Sans.zip
        mv fira_sans /usr/share/fonts/
        fc-cache -fv
      shell: bash

    - name: Cache Hugo
      id: cache-hugo
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/hugo-cache
        key: hugo-${{ inputs.hugo_version }}
    - name: Install Hugo
      if: steps.cache-hugo.outputs.cache-hit != 'true'
      env:
        HUGO_VERSION: ${{ inputs.hugo_version }}
      run: |
        HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        mkdir $HOME/bin
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
        tar xvzf ${HUGO_DOWNLOAD} hugo
        mv hugo $HOME/hugo
      shell: bash
