baseurl = "https://jasonraimondi.com"
title = "Software Engineer"
enableEmoji = true
copyright = "© 2025 Jason Raimondi"

timeout = 120000

# disqusShortname = "jasonraimondi"

pygmentsCodeFences=true
pygmentsUseClasses=true

defaultContentLanguage = "en"
ignorefiles = []

[pagination]
pagerSize=15

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

# allows html in md files, stops "raw HTML omitted"
[markup.goldmark.renderer]
  unsafe = true

[outputs]
home = ["HTML", "RSS", "SITEMAP"]

[Params]
  title = "jasonraimondi.com"
  description = "My name is Jason Raimondi and I am a Full Stack Software Engineer. My professional focus has been in web systems; everything from designing to building and deploying server and client web applications. What I really am is a technologist and all around computer geek. Give me a computer and I will be hacking in minutes, occupied for days."
  name = "Jason Raimondi"
  email = "jason@raimondi.us"
  analyticsSnippet = """
<script defer data-domain="jasonraimondi.com" src="https://plausible.io/js/plausible.js"></script>
<script defer data-domain="jasonraimondi.com" src="https://plausible.io/js/plausible.outbound-links.js"></script>
"""

[Params.ProfileURL]
  smallJPG = "/misc/me/zombie-ruby-trimmed@1x.png"
  smallWEBP = "/misc/me/zombie-ruby-trimmed@1x.webp"
  largeJPG = "/misc/me/zombie-ruby-trimmed@2x.png"
  largeWEBP = "/misc/me/zombie-ruby-trimmed@2x.webp"

[Params.EditLink]
  name = "GitHub"
  link = "https://github.com/jasonraimondi/jasonraimondi"

[module]
  [[module.mounts]]
    source = "content/resume.json"
    target = "assets/resume.json"
  [[module.mounts]]
    source = "assets"
    target = "assets"
