baseurl = "https://jasonraimondi.com"
title = "Software Engineer"
enableEmoji = true
copyright = "© 2023 Jason Raimondi"

paginate = 15
timeout = 120000

# disqusShortname = "jasonraimondi"

pygmentsCodeFences=true
pygmentsUseClasses=true

defaultContentLanguage = "en"
ignorefiles = []

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

# allows html in md files, stops "raw HTML omitted"
[markup.goldmark.renderer]
  unsafe = true

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
# order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "aws3"
URL = "s3://jasonraimondi-com-62a80b1e-61f2-4010-843d-48ba047503e8n?region=us-east-2"
cloudFrontDistributionID = "EBQ4EZAMJP74N"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|webp|gif)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|txt|xml|json)$"
gzip = true

[outputs]
home = ["HTML", "RSS"]

[Params]
  title = "jasonraimondi.com"
  description = "My name is Jason Raimondi and I am a Full Stack Software Engineer. My professional focus has been in web systems; everything from designing to building and deploying server and client web applications. What I really am is a technologist and all around computer geek. Give me a computer and I will be hacking in minutes, occupied for days."
  name = "Jason Raimondi"
  email = "jason@raimondi.us"
  analyticsSnippet = """
<script defer data-domain="jasonraimondi.com" src="https://plausible.io/js/plausible.js"></script>
<script defer data-domain="jasonraimondi.com" src="https://plausible.io/js/plausible.outbound-links.js"></script>
"""

[Params.ProfileURL]
  smallJPG = "/misc/me/zombie-ruby-trimmed@1x.png"
  smallWEBP = "/misc/me/zombie-ruby-trimmed@1x.webp"
  largeJPG = "/misc/me/zombie-ruby-trimmed@2x.png"
  largeWEBP = "/misc/me/zombie-ruby-trimmed@2x.webp"

[Params.EditLink]
  name = "GitHub"
  link = "https://github.com/jasonraimondi/jasonraimondi"
