baseurl = "https://jasonraimondi.com"
title = "Software Engineer"
languageCode = "en-us"
enableEmoji = true
copyright = "© 2022 Jason Raimondi"

paginate = 15
timeout = 120000

# disqusShortname = "jasonraimondi"

pygmentsCodeFences=true
pygmentsUseClasses=true

defaultContentLanguage = "en"
ignorefiles = [ "content/.obsidian/.*" ]

[Params]
  title = "jasonraimondi.com"
  description = "My name is Jason Raimondi and I am a Full Stack Software Engineer. My professional focus has been in web systems; everything from designing to building and deploying server and client web applications. What I really am is a technologist and all around computer geek. Give me a computer and I will be hacking in minutes, occupied for days."
  name = "Jason Raimondi"
  email = "jason@raimondi.us"
  analyticsSnippet = """
<script defer data-domain="jasonraimondi.com" src="https://plausible.io/js/plausible.js"></script>
<script defer data-domain="jasonraimondi.com" src="https://plausible.io/js/plausible.outbound-links.js"></script>
"""

[Params.ProfileURL]
  smallJPG = "/misc/me/zombie-ruby-trimmed@1x.png"
  smallWEBP = "/misc/me/zombie-ruby-trimmed@1x.webp"
  largeJPG = "/misc/me/zombie-ruby-trimmed@2x.png"
  largeWEBP = "/misc/me/zombie-ruby-trimmed@2x.webp"

[Params.EditLink]
  name = "GitHub"
  link = "https://github.com/jasonraimondi/jasonraimondi"

[Params.MainMenu]
[[Params.MainMenu.Link]]
  name = "Posts"
  url = "/posts"
[[Params.MainMenu.Link]]
  name = "Apps"
  url = "/things"
[[Params.MainMenu.Link]]
  name = "Uses"
  url = "/uses"

[Params.Projects]
[[Params.Projects.Link]]
  name = "🔐 typescript-oauth2-server"
  url = "https://github.com/jasonraimondi/ts-oauth2-server"
  description = "A standards compliant implementation of an OAuth 2.0 authorization server for Node that utilizes JWT and Proof Key for Code Exchange (PKCE), written in TypeScript. "
[[Params.Projects.Link]]
  name = "👀 promise-watch"
  url = "https://github.com/promise-watch/promise-watch"
  description = "An Api/E2E monitor that runs promises on intervals and sends notifications on errors."
[[Params.Projects.Link]]
  name = "🖼️ url-to-png"
  url = "https://github.com/jasonraimondi/url-to-png"
  description = "Dynamic screenshots for the web over a simple http api"
[[Params.Projects.Link]]
  name = "🧭 traverse"
  url = "/posts/traverse-2-electric-boogaloo"
  description = "Desktop app for explore trending GitHub repos (Mac OS/Linux)"
[[Params.Projects.Link]]
  name = "🔧 @jmondi/packages"
  url = "https://github.com/jasonraimondi/jmondi"
  description = "A collection of utility packages for use in a variety of projects. "
[[Params.Projects.Link]]
  name = "🗺️ locatizor"
  url = "https://github.com/jasonraimondi/locatizor"
  description = "Desktop app to add GPS data to jpg's that are missing location (Mac OS/Linux)"
[[Params.Projects.Link]]
  name = "💼 restforce-php"
  url = "https://github.com/eventfarm/restforcephp"
  description = "PHP API client library for Salesforce"

[Params.ExternalMenu]
  title = "Follow Me Online Here:"
[[Params.ExternalMenu.Link]]
  name = "GitHub"
  url = "https://github.com/jasonraimondi"
[[Params.ExternalMenu.Link]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/jasonraimondi"
[[Params.ExternalMenu.Link]]
  name = "Vimeo"
  url = "https://vimeo.com/jasonraimondi"

[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

# allows html in md files, stops "raw HTML omitted"
[markup.goldmark.renderer]
  unsafe = true

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
# order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "aws3"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
# URL = "gs://<Bucket Name>"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://jasonraimondi-com-62a80b1e-61f2-4010-843d-48ba047503e8n?region=us-east-2"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

# You can use a "prefix=" query parameter to target a subfolder of the bucket:
# URL = "gs://<Bucket Name>?prefix=a/subfolder/"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "EBQ4EZAMJP74N"

# Optionally, you can include or excmlude specific files.
# See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# If non-empty, the pattern is matched against the local path.
# All paths are matched against in their filepath.ToSlash form.
# If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
# If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
# As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
# and remote files that don't pass the include/exclude filters are not deleted.
# include = "**.html" # would only include files with ".html" suffix
# exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|webp|gif)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|txt|xml|json)$"
gzip = true

[outputs]
home = ["HTML", "RSS"]
