baseurl: ""

title: Jason Raimondi | Software Engineer
email: jason@raimondi.us
short_description: Jason Raimondi is a Software Engineer based out of California.
description: >-
  My name is Jason Raimondi and I am a Full Stack Software Engineer from the east coast, living on the west coast. My primary professional focus has been in web technologies, designing, building and deploying web applications. Really, I am a technologist and all around computer geek, give me a computer and I will be hacking in minutes and occupied for days.
url: "https://jasonraimondi.com"

profile_url: "https://jasonraimondi.com/assets/misc/me/avatar.png"

twitter_username: jsonmamondi
github_username:  jasonraimondi

timezone: America/Los_Angeles
permalink: /posts/:title
plugins:
- jekyll-feed
- jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
# Add additional excludes here
- .gitignore
