name: deploy to s3

on:
  push:
    paths-ignore:
      - '.github/workflows/regenerate_resume.yml'
      - 'content/resume.json'
      - 'resume-snapshotter.ts'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          hugo_version: "0.120.3"
      - run: pnpm install --frozen-lockfile
      - uses: ./.github/actions/build_and_deploy
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
