name: deploy to s3

env:
  HUGO_VERSION: 0.116.0

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: "8.x"
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          registry-url: "https://registry.npmjs.org"
      - name: Install Google Fonts
        run: |
          wget -O Fira_Sans.zip https://fonts.google.com/download?family=Fira%20Sans
          unzip -d fira_sans/ Fira_Sans.zip
          mv fira_sans /usr/share/fonts/
          fc-cache -fv
      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          mkdir $HOME/bin
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
      - run: pnpm install --frozen-lockfile --production false
      - run: npx playwright install --with-deps
      - run: pnpm gen:resume:ci
      - run: $HOME/hugo --gc --cleanDestinationDir
      - name: Deploy to S3
        if: github.ref == 'refs/heads/main'
        run: $HOME/hugo -v deploy --maxDeletes -1 --invalidateCDN true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
