name: deploy to s3

env:
  HUGO_VERSION: 0.117.0

on:
  push:
    paths-ignore:
      - '.github/workflows/regenerate_resume.yml'
      - 'content/resume.json'
      - 'resume-snapshotter.ts'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm install --frozen-lockfile
      - uses: ./.github/actions/build_and_deploy
